### ISSUE TITLE
Not enough arguments in call main.go:31 (LoadTrueType)

### ISSUE THREAD

**Issue by hbyscx001** [ntop001/flappybird#2]
../src/github.com/ntop001/flappybird/main.go:31:25: not enough arguments in call to "korok.io/korok/asset".Font.LoadTrueType
	have (string, string)
	want (string, string, font.TTFConfig)

**Comment by ntop001** [comment]
@hbyscx001 The code is a little outdated. I'll update it latter. For a quick fix, use
```
LoadTrueType("font-file", font.ASCII(32))
``` 
`font.ASCII(32)` will return a config, 32 is the default font size.   In the old LoadTrueType() function, it use a hardcoded charset and font-size.
